name: Docker Image TZ Implementation CI

on:
  push:
    branches: ["implementation/tz/develop"]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the TZ implementation Docker image
        run: |
          docker build . --tag ghcr.io/openimis/openimis-fe:${GITHUB_REF##*/}
          docker run ghcr.io/openimis/openimis-fe:${GITHUB_REF##*/} nginx -t 
          docker push ghcr.io/openimis/openimis-fe:${GITHUB_REF##*/}
