name: create manual docker image 
on:
  workflow_dispatch:
    inputs:   
      tag:
        required: true

jobs:
  publish-manual-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the openimis backend Docker image
      run: |
         docker build --tag ghcr.io/blsq/openimis-fe:${{ github.event.inputs.tag }} --build-arg ssh_lang_key="${{ secrets.SSH_KEY_LANGUAGE_MODULE }}" --squash .
         docker push ghcr.io/blsq/openimis-fe:${{ github.event.inputs.tag }}
